name = "loga"
description = "Simple library for logging some data"
version = "1.0.0"

authors = ["Cyrill Korshnyak ł"]
maintainers = ["Cyrill Korshnyak <kirilkorshnyak@yandex.ru>"]
maintainers-logins = ["mangl-auf"]
