name = "loga"
description = "Simple library for simple logging. Like npm package \"debug\", but for Ada"
version = "1.2.0"

authors = ["Cyrill Korshnyak ł"]
maintainers = ["Cyrill Korshnyak <kirillkorshnyak@yandex.com>"]
maintainers-logins = ["mangl-auf"]
tags = ["logging"]
website = "https://github.com/mangl-auf/loga/"
licenses = "Unlicense"
